models:
  - type: main
    engine: ollama
    model: "llama3.2"
    parameters:
      base_url: "http://172.26.64.1:11434"

rails:
  input:
    flows:
      - check input safety
      - check input scope
