models:
  - type: main
    engine: langchain
    model: ChatOllama
    parameters:
      base_url: "http://172.26.64.1:11434"
      model: "llama3.2"

rails:
  input:
    flows:
      - check input safety
      - check input scope
